### ISSUE TITLE
dedicated layout for local news

### ISSUE THREAD

**Issue by mehimself** [centre-for-humanities-computing/websiteMedia#22]

**Comment by LineCHC** [comment]
Could you do the design as https://neic.no/news/2021/09/24/nordic-pandemic-research-infrastructure/ using approximately 2/3 of width for text and image content, and 1/3 for our “news feed” element from the IHPC front page. This solves the issue with excessive line-length for these pages. Having the date above the heading like neic would also be good.

**Comment by safinazbg** [comment]
-Grid column layout 2/3 1/3 for article body and featured news list
